[theme]
base = "dark"
primaryColor = "#ff9900"
backgroundColor = "#111111"
secondaryBackgroundColor = "#181818"
textColor = "#f5f5f5"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false